version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/opt/go/code
      - ~/etc/localtime:/opt/ucare/etc/localtime
      - ~/etc/timezone:/opt/ucare/etc/timezone
    command: ["tail -f /dev/null"]
    ports:
      - 3722:8000

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sqls/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql